version: "3"

services:
  robot-user:
    build:
        context: ..
        dockerfile: docker/frob.dockerfile
    container_name: ros
    ports:
      - 11311:11311
    network_mode: host
    extra_hosts:
        - robot:192.168.129.29
        - robot-user:10.100.102.7
    environment:
        - DISPLAY=${DISPLAY}
        - ROS_MASTER_URI=http://robot-user:11311
        - ROS_HOSTNAME=robot-user
        - ROS_IP:192.168.129.190
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    hostname: robot-user

volumes:
  x11:
