slam_toolbox:
  ros__parameters:
    use_sim_time: True
    slam_mode: mapping
    publish_map: True
    resolution: 0.05
    map_update_interval: 5.0
    use_scan_matching: True
    map_frame: map
    odom_frame: odom
    scan_topic: '/scan'
    odom_topic: '/odom'    
    base_frame: base_link
    publish_tf: True
    transform_timeout: 0.1
    max_laser_range: 10.0
    minimum_travel_distance: 0.01
    minimum_travel_heading: 0.01
    queue_size: 10
    transform_timeout: 1
    map_update_interval: 0.3
    log_level: "debug"
